# Makefile extensions for linux.

# -----------------------------------------------------------------------------
# Makefile targets supported by all platforms.
# -----------------------------------------------------------------------------

.PHONY: hello-world
hello-world:
	@echo "Hello World, from linux."

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

.PHONY: build
build: linux/amd64

# -----------------------------------------------------------------------------
# Makefile targets supported only by this platform.
# -----------------------------------------------------------------------------

.PHONY: only-linux
only-linux:
	@echo "Only linux has this Makefile target."