# Makefile extensions for darwin.

# -----------------------------------------------------------------------------
# Makefile targets supported by all platforms.
# -----------------------------------------------------------------------------

.PHONY: hello-world
hello-world:
	@echo "Hello World, from darwin."

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

.PHONY: build
build: darwin/amd64

# -----------------------------------------------------------------------------
# Utility targets
# -----------------------------------------------------------------------------

.PHONY: setup
setup:
	@rm -rf /tmp/sqlite
	@mkdir  /tmp/sqlite
	@touch  /tmp/sqlite/G2C.db

# -----------------------------------------------------------------------------
# Makefile targets supported only by this platform.
# -----------------------------------------------------------------------------

.PHONY: only-darwin
only-darwin:
	@echo "Only darwin has this Makefile target."
