---

name: 'call dependabot approve and merge'

on: 
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-dependabot-approve-and-merge:
    uses: Senzing/build-resources/.github/workflows/dependabot-approve-and-merge.yaml@main
    secrets:
      CODEOWNER_PR_APPROVAL_TOKEN: ${{ secrets.CODEOWNER_PR_APPROVAL_TOKEN }}