# Based on
# -https://github.com/marketplace/actions/setup-go-environment

name: go-test.yaml

on: [push]

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib
  SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    name: Testing with Go ${{ matrix.go }}
    services:
      postgres:
        env:
          POSTGRESQL_DATABASE: G2
          POSTGRESQL_PASSWORD: senzing
          POSTGRESQL_POSTGRES_PASSWORD: postgres
          POSTGRESQL_USERNAME: senzing
        image: bitnami/postgresql
        ports:
          - 5432:5432
      mssql:
        env:
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
          MSSQL_SA_PASSWORD: Passw0rd
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
      mysql:
        env:
          MYSQL_DATABASE: G2
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: mysql
        image: bitnami/mysql
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: pwd
      - run: env
      - run: mkdir /tmp/sqlite
      - run: touch /tmp/sqlite/G2C.db
      - run: go test -v -p 1 ./...
